apiVersion: v1
kind: Service
metadata:
  name: future-battlegrounds
  labels:
    run: future-battlegrounds
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  - port: 50051
    protocol: TCP
    name: grpc
  selector:
    app: future-battlegrounds